<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>sim</name>
  <version>0.1.0</version>
  <description>Launches gz sim (Gazebo Harmonic) with the ARCC_Field_2026 world and spawns the sentry robot from URDF/xacro.</description>
  <maintainer email="baptisbc@RHIT.edu">Thornbots</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <depend>ros_gz_interfaces</depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>foxglove_bridge</exec_depend>
  <depend>tf2_msgs</depend>
  <depend>rclcpp</depend>
  <depend>rcl_interfaces</depend>
  <depend>ament_index_cpp</depend>
  <depend>builtin_interfaces</depend>
  <depend>tf2_ros</depend>
  <depend>eigen</depend>
  <depend>rclpy</depend>
  <depend>ament_index_python</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>python3-numpy</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_srvs</depend>
  <depend>dji_serial_bridge</depend>
  <depend>visualization_msgs</depend>
  <depend>rosgraph_msgs</depend>
  <depend>realsense2_camera_msgs</depend>
  <depend>rclcpp_components</depend>
  <depend>rosidl_typesupport_introspection_cpp</depend>
  <depend>urdf</depend>
  <depend>vision_msgs</depend>
  <depend>gz_msgs_vendor</depend>
  <depend>gz_transport_vendor</depend>
  <depend>gz_sim_vendor</depend>
  <depend>gz_plugin_vendor</depend>
  <depend>tinyxml2_vendor</depend>
  <depend>diagnostic_msgs</depend>

  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
