#!/usr/bin/env python3
# Copyright 2026 Thornbots
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Print test/cv/estimation_limits_data.py from the estimation bench runs' estimation.jsonl.

`python3 tools/estimation_limits.py RUN_DIR ... > test/cv/estimation_limits_data.py`,
each RUN_DIR a log_dir:=, any mix of cases. Limit per cell and metric = worst
p95 over the runs that scored the cell x (1 + margin), 2x by default: a run
strays up to ~2x from the others (2026-09-27, leave-one-out). Never under
--floor, so a metric that reads exactly 0 (a still target's velocity) doesn't
fail on any noise. Cells from fewer than three runs are flagged
(CV_SPLIT_PLAN.md 2.0). `--keep test/cv/estimation_limits_data.py` carries
over, verbatim, every cell these runs don't score, and that file's run list.
"""
import argparse
import collections
import json
import os
import re
import sys
import textwrap

# estimation_metrics.METRICS
METRICS = ('facing_panel_m', 'panel_m', 'center_m', 'center_along_m', 'center_across_m',
           'velocity_m_s', 'yaw_rad', 'yaw_rate_rad_s', 'radius_m', 'z_offset_m')


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument('runs', nargs='+', help='log dirs, one per run')
    parser.add_argument('--margin', type=float, default=1.0)
    parser.add_argument('--floor', type=float, default=0.02, help='m, rad, m/s or rad/s')
    parser.add_argument('--keep', help='a generated file whose other cells to keep')
    args = parser.parse_args(argv)

    p95 = collections.defaultdict(lambda: collections.defaultdict(list))
    seen = collections.Counter()
    for run in args.runs:
        with open(os.path.join(run, 'estimation.jsonl')) as f:
            for line in f:
                rec = json.loads(line)
                seen[rec['cell']] += 1
                for key in METRICS:
                    if rec.get(key):
                        p95[rec['cell']][key].append(rec[key]['p95'])

    kept, kept_runs = {}, []
    if args.keep:
        with open(args.keep) as f:
            text = f.read()
        blocks = re.findall(r"^(    '([^']+)': \{.*?^    \},\n)", text, re.M | re.S)
        kept = {cell: block for block, cell in blocks if cell not in p95}
        header = re.search(r'^# Runs: (.*?)\nLIMITS', text, re.M | re.S).group(1)
        kept_runs = [r.strip() for r in header.replace('\n# ', ' ').split(',')]

    with open(__file__) as f:
        print(f.read().split('"""')[0], end='')  # the license header
    print('"""Generated by tools/estimation_limits.py; regenerate, do not edit."""\n')
    print('# Steady-state p95 limits per cell, metric -> m, rad, m/s or rad/s: the worst\n'
          f'# run x {1.0 + args.margin:g}, floored at {args.floor:g}. '
          "Comments list each run's p95.")
    runs = kept_runs + [os.path.basename(os.path.normpath(r)) for r in args.runs]
    names = ', '.join(dict.fromkeys(runs))
    print(textwrap.fill(names, 79, initial_indent='# Runs: ', subsequent_indent='# '))
    print('LIMITS = {')
    for cell in sorted(set(p95) | set(kept)):
        if cell in kept:
            print(kept[cell], end='')
            continue
        note = '' if seen[cell] >= 3 else f'  # {seen[cell]} runs only'
        print(f"    '{cell}': {{{note}")
        for key, values in p95[cell].items():
            limit = max(max(values) * (1.0 + args.margin), args.floor)
            print(f"        '{key}': {limit:.4f},"
                  f"  # {', '.join(f'{v:.4f}' for v in values)}")
        print('    },')
    print('}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
