// Copyright 2026 Thornbots
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include <iomanip>
#include <iostream>
#include <map>
#include <regex>
#include <set>
#include "sim/tool_io.hpp"

int main(int argc, char **argv) {
  try {
    double margin = 1.0, floor = 0.02;
    std::string keep;
    std::vector<std::string> runs, kept_runs;
    for (int i = 1; i < argc; ++i) {
      const std::string arg = argv[i];
      if (arg == "--margin" && i + 1 < argc) margin = std::stod(argv[++i]);
      else if (arg == "--floor" && i + 1 < argc) floor = std::stod(argv[++i]);
      else if (arg == "--keep" && i + 1 < argc) keep = argv[++i];
      else runs.push_back(arg);
    }
    if (runs.empty()) { std::cerr << "usage: estimation_limits RUN [RUN ...] [--margin N] [--floor N] [--keep HEADER]\n"; return 2; }
    const std::vector<std::string> metrics{"facing_panel_m", "panel_m", "center_m", "center_along_m", "center_across_m",
      "velocity_m_s", "yaw_rad", "yaw_rate_rad_s", "radius_m", "z_offset_m"};
    std::map<std::string, std::map<std::string, std::vector<double>>> p95;
    std::map<std::string, int> seen;
    for (const auto &run : runs) for (const auto &r : sim::tools::json_lines(std::filesystem::path(run) / "estimation.jsonl")) {
      const auto cell = r.at("cell").get<std::string>();
      ++seen[cell];
      for (const auto &key : metrics) if (r.contains(key) && !r.at(key).is_null() && !r.at(key).empty())
        p95[cell][key].push_back(r.at(key).at("p95").get<double>());
    }
    std::map<std::string, std::string> kept;
    if (!keep.empty()) {
      const auto content = sim::tools::read(keep);
      const std::regex block(R"re([ \t]*\{"([^"]+)", \{[\s\S]*?\}\},[^\n]*\n)re");
      for (auto i = std::sregex_iterator(content.begin(), content.end(), block); i != std::sregex_iterator(); ++i)
        if (!p95.count((*i)[1])) kept[(*i)[1]] = i->str();
      std::istringstream lines(content);
      std::string line;
      while (std::getline(lines, line)) if (line.rfind("// Runs: ", 0) == 0) {
        std::istringstream names(line.substr(9));
        while (std::getline(names, line, ',')) {
          const auto start = line.find_first_not_of(' ');
          if (start != std::string::npos) kept_runs.push_back(line.substr(start));
        }
      }
    }
    std::cout << "// Copyright 2026 Thornbots\n// SPDX-License-Identifier: Apache-2.0\n#pragma once\n"
      "#include <map>\n#include <string>\n\n// Generated by estimation_limits; regenerate, do not edit.\n"
      "// Steady-state p95: worst run x " << 1 + margin << ", floored at " << floor << ".\n// Runs: ";
    std::set<std::string> names;
    bool first = true;
    for (const auto &run : runs) kept_runs.push_back(std::filesystem::path(run).lexically_normal().filename().string());
    for (const auto &name : kept_runs) if (names.insert(name).second) { std::cout << (first ? "" : ", ") << name; first = false; }
    std::cout << "\nnamespace sim::cv_bench {\ninline const std::map<std::string, std::map<std::string, double>> LIMITS = {\n";
    std::set<std::string> cells;
    for (const auto &v : p95) cells.insert(v.first);
    for (const auto &v : kept) cells.insert(v.first);
    std::cout << std::fixed << std::setprecision(4);
    for (const auto &cell : cells) {
      if (kept.count(cell)) { std::cout << kept.at(cell); continue; }
      std::cout << "    {\"" << cell << "\", {";
      if (seen[cell] < 3) std::cout << "  // " << seen[cell] << " runs only";
      std::cout << '\n';
      for (const auto &key : metrics) if (p95[cell].count(key)) {
        const auto &values = p95[cell].at(key);
        std::cout << "        {\"" << key << "\", " << std::max(*std::max_element(values.begin(), values.end()) * (1 + margin), floor) << "},  // ";
        for (std::size_t i = 0; i < values.size(); ++i) std::cout << (i ? ", " : "") << values[i];
        std::cout << '\n';
      }
      std::cout << "    }},\n";
    }
    std::cout << "};\n}  // namespace sim::cv_bench\n";
    return 0;
  } catch (const std::exception &e) { std::cerr << e.what() << '\n'; return 1; }
}
